# Generated by Django 2.2.6 on 2019-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('publish', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Categoryinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUTIME', models.CharField(max_length=50, null=True)),
                ('TRANSCODE', models.CharField(max_length=10, null=True)),
                ('TRANSETYPE', models.CharField(max_length=20, null=True)),
                ('MARKETCODE', models.CharField(max_length=20, null=True)),
                ('MARKET', models.CharField(max_length=20, null=True)),
                ('LISTINGSTATE', models.CharField(max_length=20, null=True)),
                ('TRANSUNIT', models.CharField(max_length=30, null=True)),
                ('PRICEUNIT', models.CharField(max_length=30, null=True)),
                ('MINPCHANGE', models.CharField(max_length=30, null=True)),
                ('CONTRADATE', models.CharField(max_length=50, null=True)),
                ('TRANSDATE', models.CharField(max_length=200, null=True)),
                ('LTRANSDATE', models.CharField(max_length=100, null=True)),
                ('DELIVERYDATE', models.CharField(max_length=100, null=True)),
                ('TRANSMARGIN', models.CharField(max_length=20, null=True)),
                ('PRICELIMIT', models.CharField(max_length=100, null=True)),
                ('DELIVLOACT', models.CharField(max_length=50, null=True)),
                ('DELIVMETHOD', models.CharField(max_length=50, null=True)),
                ('DELIVGRADE', models.CharField(max_length=500, null=True)),
                ('TRANSFEE', models.CharField(max_length=50, null=True)),
                ('DELIVUNIT', models.CharField(max_length=50, null=True)),
                ('MINDUNIT', models.CharField(max_length=50, null=True)),
                ('CURRENCY', models.CharField(max_length=20, null=True)),
                ('CONTRTYPE', models.CharField(max_length=20, null=True)),
                ('CONTRSUBTYPE', models.CharField(max_length=30, null=True)),
                ('HYCS', models.CharField(max_length=20, null=True)),
                ('ZXDBJ', models.CharField(max_length=20, null=True)),
                ('BZJB', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'categoryinfo',
            },
        ),
        migrations.CreateModel(
            name='ExchangeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INIT_DATE', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'exchange_date',
            },
        ),
        migrations.CreateModel(
            name='MainContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, null=True)),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('instrumentId', models.CharField(max_length=20, null=True)),
                ('tradingDay', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'maincontract',
            },
        ),
        migrations.CreateModel(
            name='Tick_1min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRADINGDAY', models.CharField(max_length=30, null=True)),
                ('INSTRUMENTID', models.CharField(max_length=20, null=True)),
                ('EXCHANGEID', models.CharField(max_length=10, null=True)),
                ('CLOSEPRICE', models.FloatField(null=True)),
                ('OPENPRICE', models.FloatField(null=True)),
                ('HIGHESTPRICE', models.FloatField(null=True)),
                ('LOWESTPRICE', models.FloatField(null=True)),
                ('VOLUME', models.FloatField(null=True)),
                ('CHANGEAMOUT', models.FloatField(null=True)),
                ('CHANGERATE', models.FloatField(null=True)),
                ('TURNOVER', models.FloatField(null=True)),
                ('OPENINTEREST', models.FloatField(null=True)),
                ('SETTLEMENTPRICE', models.FloatField(null=True)),
                ('UPDATETIME', models.CharField(max_length=30, null=True)),
                ('AVERAGEPRICE', models.FloatField(null=True)),
                ('ACTIONDAY', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'tick_1min',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=20, null=True)),
                ('avatar', models.CharField(max_length=100, null=True)),
                ('signature', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('notifyCount', models.IntegerField(null=True)),
                ('unreadCount', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=120, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('InitialInterest', models.FloatField(null=True)),
                ('bond', models.FloatField(null=True)),
                ('profitInPosition', models.FloatField(null=True)),
                ('profitInClosePosition', models.FloatField(null=True)),
                ('currentInterest', models.FloatField(null=True)),
                ('availableFund', models.FloatField(null=True)),
                ('profile', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
